[2025-01-01 18:29:35.793747] Error: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /api/sync_canteen (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000015FC826DD20>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
[2025-01-01 18:29:39.858845] Error: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /api/sync_slp (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000015FC826E890>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
[2025-01-01 18:29:43.941507] Error: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /api/sync_employee (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000015FC826F340>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
[2025-01-01 18:29:48.041162] Error: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /api/sync_employee_cc (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000015FC826F5E0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
[2025-01-01 18:29:52.112844] Error: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /api/sync_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000015FC826E800>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
[2025-01-03 14:20:10.058078] Error: HTTPConnectionPool(host='192.168.100.199', port=80): Max retries exceeded with url: /api/sync_canteen (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002759FD2B250>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
[2025-01-03 14:20:12.072979] Error: HTTPConnectionPool(host='192.168.100.199', port=80): Max retries exceeded with url: /api/sync_slp (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002759FD2BD90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
